### ISSUE TITLE
BLS To Execution Change "Command line with flags" typo

### ISSUE THREAD

**Issue by calumtomeny** [ethereum/staking-launchpad#621]
In the example with flags, the `bls_withdrawal_credentials_list` value contains two withdrawal credentials with a "0x" prefix. This prefix should not be used and if it is, the user is shown an error - when the prefix is omitted, the json file is generated successfully (assuming all other parameters are correct.

**Comment by calumtomeny** [comment]
The issue is fixed with pull #620.

**Comment by wackerow** [comment]
@calumtomeny Thanks for reporting... can you confirm you're using the [latest release](https://github.com/ethereum/staking-deposit-cli/releases/tag/v2.5.0) of the `staking-deposit-cli` (`v2.5.0`)?

I just tried this with the demo example and it succeeded without error:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/54227730/229912025-8add4e2d-d9af-4d39-aeca-6ccd4649f298.png">

@hwwhww Can you confirm the `staking-deposit-cli` supports both forms? I thought I remember seeing somewhere on that repo that the script should support both with or without the `0x`.

**Comment by calumtomeny** [comment]
@wackerow I was using version v2.5.0 and I was copying my withdrawal credentials from the beaconcha.in website - this is an example of the page I was copying it from: https://beaconcha.in/validator/5000#deposits. I tried this multiple times without success and I only managed to succeed by regenerating my validator key files and copying the withdrawal credentials from these files. The only difference I could see between the beaconcha.in withdrawal credential and the credential in the validator file was the omission of "0x" in the validator file which worked for me.

**Comment by wackerow** [comment]
Hm, interesting, thanks for the update. I'm still not getting this error on my end... @calumtomeny would you mind also noting the OS you're using, or even what terminal software you're using?

I'm using latest macOS with the default terminal using bash. If I use the Copy button on Beaconcha.in to copy the withdrawal credentials as you noted, I do not receive an error (while keeping the `0x` in the string). I'm wondering if there is something funky going on when you try to paste your clipboard into your terminal. 

@hwwhww Have you come across this at all?

**Comment by calumtomeny** [comment]
@wackerow I got some time to try again today and everything worked great - the only difference being the order of the validator indices. The correct order for the indices wasn't numerical order and I had them in numerical order previously (which was wrong), taking your example the validator indices would be "50001, 50000" - correct indices but in the wrong order. I only found that this was wrong when I broadcast the message. I can't see how the wrong order would've caused an issue to not allow the `0x` prefix - if your example works when swapping the indices then I probably did something else wrong at the time that I can't identify now. Thanks for your help with this.

**Comment by wackerow** [comment]
Thanks for clarifying! I'm going to go ahead and close this out now, appreciate you reporting the issue
